/** Fixed catalogue. Prices in Indonesian rupiah, formatted with Intl at the call site. */

export type Category = 'bags' | 'shoes' | 'clothing' | 'accessories';

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: Category;
  price: number;
  was?: number;
  rating: number;
  reviews: number;
  colour: string;
  size: string[];
  condition: 'new' | 'used';
  stock: number;
  blurb: string;
}

export const products: Product[] = [
  {
    id: 'round-glasses',
    category: 'accessories',
    name: 'Round Glasses',
    brand: 'Dusk',
    price: 289000,
    was: 349000,
    rating: 4.6,
    reviews: 128,
    colour: 'Gold',
    size: ['S', 'M'],
    condition: 'new',
    stock: 6,
    blurb: 'Thin metal frame, spring hinges, and a case that survives a rucksack.',
  },
  {
    id: 'bucket-hat',
    category: 'accessories',
    name: 'Canvas Bucket Hat',
    brand: 'Thicket',
    price: 165000,
    rating: 4.2,
    reviews: 64,
    colour: 'Green',
    size: ['M', 'L'],
    condition: 'new',
    stock: 22,
    blurb: 'Heavy canvas, unlined, and it packs flat.',
  },
  {
    id: 'crossbody-bag',
    category: 'bags',
    name: 'Everyday Crossbody Bag',
    brand: 'Dusk',
    price: 420000,
    rating: 4.8,
    reviews: 311,
    colour: 'Black',
    size: ['M'],
    condition: 'new',
    stock: 3,
    blurb: 'Two compartments, one of them padded for a 13-inch laptop.',
  },
  {
    id: 'canvas-sneakers',
    category: 'shoes',
    name: 'Low Canvas Sneakers',
    brand: 'Stride',
    price: 535000,
    was: 640000,
    rating: 4.4,
    reviews: 92,
    colour: 'White',
    size: ['S', 'M', 'L'],
    condition: 'new',
    stock: 11,
    blurb: 'Vulcanised sole, cotton laces, and a toe box that is actually wide.',
  },
  {
    id: 'denim-jacket',
    category: 'clothing',
    name: 'Classic Denim Jacket',
    brand: 'Thicket',
    price: 725000,
    rating: 4.1,
    reviews: 47,
    colour: 'Blue',
    size: ['M', 'L', 'XL'],
    condition: 'used',
    stock: 1,
    blurb: 'Rigid denim, unwashed, and it will fade exactly where you bend.',
  },
  {
    id: 'plain-tee',
    category: 'clothing',
    name: 'Plain Cotton Tee',
    brand: 'Stride',
    price: 119000,
    rating: 4.0,
    reviews: 508,
    colour: 'White',
    size: ['S', 'M', 'L', 'XL'],
    condition: 'new',
    stock: 84,
    blurb: 'Combed cotton, side-seamed, and it does not twist in the wash.',
  },
  {
    id: 'cargo-trousers',
    category: 'clothing',
    name: 'Cargo Trousers',
    brand: 'Thicket',
    price: 389000,
    rating: 3.9,
    reviews: 73,
    colour: 'Cream',
    size: ['M', 'L'],
    condition: 'new',
    stock: 9,
    blurb: 'Six pockets, and two of them fit a phone the right way up.',
  },
  {
    id: 'leather-wallet',
    category: 'accessories',
    name: 'Folding Leather Wallet',
    brand: 'Dusk',
    price: 245000,
    rating: 4.7,
    reviews: 154,
    colour: 'Brown',
    size: ['M'],
    condition: 'new',
    stock: 17,
    blurb: 'Vegetable-tanned, four card slots, and no coin pocket on purpose.',
  },
  {
    id: 'knitted-scarf',
    category: 'accessories',
    name: 'Knitted Scarf',
    brand: 'Stride',
    price: 179000,
    rating: 4.3,
    reviews: 38,
    colour: 'Red',
    size: ['M'],
    condition: 'used',
    stock: 4,
    blurb: 'Lambswool, ribbed, and long enough to actually wrap twice.',
  },

  {
    id: 'daypack',
    category: 'bags',
    name: '22L Daypack',
    brand: 'Thicket',
    price: 540000,
    rating: 4.5,
    reviews: 203,
    colour: 'Black',
    size: ['M'],
    condition: 'new',
    stock: 9,
    blurb: 'One laptop sleeve, one bottle pocket, and a back panel that breathes.',
  },
  {
    id: 'canvas-tote',
    category: 'bags',
    name: 'Heavy Canvas Tote',
    brand: 'Dusk',
    price: 185000,
    was: 229000,
    rating: 4.1,
    reviews: 77,
    colour: 'Cream',
    size: ['L'],
    condition: 'new',
    stock: 31,
    blurb: 'Twelve-ounce canvas, boxed corners, and handles long enough for a shoulder.',
  },
  {
    id: 'belt-bag',
    category: 'bags',
    name: 'Compact Belt Bag',
    brand: 'Stride',
    price: 215000,
    rating: 4.0,
    reviews: 45,
    colour: 'Blue',
    size: ['S', 'M'],
    condition: 'new',
    stock: 14,
    blurb: 'A phone, a wallet, keys. Deliberately nothing more.',
  },
  {
    id: 'cabin-suitcase',
    category: 'bags',
    name: '20-inch Cabin Suitcase',
    brand: 'Thicket',
    price: 1250000,
    was: 1490000,
    rating: 4.6,
    reviews: 118,
    colour: 'Black',
    size: ['L'],
    condition: 'new',
    stock: 5,
    blurb: 'Cabin size on four airlines we have measured, with wheels that do not sing.',
  },
  {
    id: 'running-shoes',
    category: 'shoes',
    name: 'Lightweight Running Shoes',
    brand: 'Stride',
    price: 680000,
    rating: 4.4,
    reviews: 266,
    colour: 'White',
    size: ['M', 'L', 'XL'],
    condition: 'new',
    stock: 12,
    blurb: 'A 220-gram shoe with a foam midsole that has not gone flat after 400 km.',
  },
  {
    id: 'hiking-sandals',
    category: 'shoes',
    name: 'Hiking Sandals',
    brand: 'Thicket',
    price: 320000,
    was: 389000,
    rating: 4.2,
    reviews: 91,
    colour: 'Green',
    size: ['M', 'L'],
    condition: 'new',
    stock: 18,
    blurb: 'Three straps, a grippy sole, and a footbed that dries overnight.',
  },
  {
    id: 'derby-shoes',
    category: 'shoes',
    name: 'Leather Derby Shoes',
    brand: 'Dusk',
    price: 890000,
    rating: 4.7,
    reviews: 143,
    colour: 'Brown',
    size: ['M', 'L'],
    condition: 'new',
    stock: 7,
    blurb: 'Goodyear welted, so it can be resoled instead of replaced.',
  },
  {
    id: 'rain-boots',
    category: 'shoes',
    name: 'Short Rain Boots',
    brand: 'Stride',
    price: 420000,
    rating: 3.9,
    reviews: 29,
    colour: 'Black',
    size: ['M', 'L'],
    condition: 'used',
    stock: 3,
    blurb: 'Second-hand, cleaned, and honest about the scuff on the left heel.',
  },
  {
    id: 'flannel-shirt',
    category: 'clothing',
    name: 'Flannel Shirt',
    brand: 'Thicket',
    price: 295000,
    was: 349000,
    rating: 4.3,
    reviews: 112,
    colour: 'Red',
    size: ['S', 'M', 'L'],
    condition: 'new',
    stock: 21,
    blurb: 'Brushed cotton, a chest pocket, and a hem that stays tucked.',
  },
  {
    id: 'knitted-jumper',
    category: 'clothing',
    name: 'Plain Knitted Jumper',
    brand: 'Dusk',
    price: 385000,
    rating: 4.5,
    reviews: 88,
    colour: 'Cream',
    size: ['M', 'L', 'XL'],
    condition: 'new',
    stock: 13,
    blurb: 'Merino blend, ribbed cuffs, and no logo anywhere on it.',
  },
  {
    id: 'chinos',
    category: 'clothing',
    name: 'Chinos',
    brand: 'Stride',
    price: 330000,
    rating: 4.1,
    reviews: 64,
    colour: 'Blue',
    size: ['S', 'M', 'L'],
    condition: 'new',
    stock: 26,
    blurb: 'A mid rise that sits where it says it will, with a little stretch.',
  },
  {
    id: 'rain-jacket',
    category: 'clothing',
    name: 'Packable Rain Jacket',
    brand: 'Thicket',
    price: 575000,
    was: 699000,
    rating: 4.6,
    reviews: 157,
    colour: 'Green',
    size: ['M', 'L', 'XL'],
    condition: 'new',
    stock: 8,
    blurb: 'Taped seams, a hood that stays up, and it folds into its own pocket.',
  },
  {
    id: 'baseball-cap',
    category: 'accessories',
    name: 'Cotton Baseball Cap',
    brand: 'Dusk',
    price: 145000,
    rating: 4.0,
    reviews: 52,
    colour: 'Black',
    size: ['M'],
    condition: 'new',
    stock: 40,
    blurb: 'Six panels, a curved brim, and a metal buckle rather than plastic.',
  },
  {
    id: 'leather-gloves',
    category: 'accessories',
    name: 'Leather Gloves',
    brand: 'Stride',
    price: 260000,
    rating: 4.4,
    reviews: 33,
    colour: 'Brown',
    size: ['S', 'M', 'L'],
    condition: 'new',
    stock: 11,
    blurb: 'Unlined lambskin that gives a little after a fortnight.',
  },
  {
    id: 'wool-socks',
    category: 'accessories',
    name: 'Wool Socks (3 pairs)',
    brand: 'Thicket',
    price: 135000,
    was: 169000,
    rating: 4.2,
    reviews: 204,
    colour: 'Cream',
    size: ['M', 'L'],
    condition: 'new',
    stock: 55,
    blurb: 'Merino, cushioned heel, and they have survived thirty washes here.',
  },
];

export const colours = ['Gold', 'Green', 'Black', 'White', 'Blue', 'Cream', 'Brown', 'Red'];
export const brands = ['Dusk', 'Thicket', 'Stride'];
export const sizes = ['S', 'M', 'L', 'XL'];

export const idr = (value: number) =>
  `Rp ${value.toLocaleString('en-GB', { maximumFractionDigits: 0 })}`;

/** What the header's navigation menu groups by, with wording for each. */
export const categories: { id: Category; label: string; blurb: string }[] = [
  { id: 'bags', label: 'Bags', blurb: 'Backpacks, totes, cabin suitcases' },
  { id: 'shoes', label: 'Shoes', blurb: 'Running, leather, sandals' },
  { id: 'clothing', label: 'Clothing', blurb: 'Shirts, jackets, trousers' },
  { id: 'accessories', label: 'Accessories', blurb: 'Hats, wallets, socks' },
];

/** One order a signed-in customer can look back at. */
export interface Order {
  id: string;
  placed: string;
  status: 'processing' | 'shipped' | 'delivered' | 'cancelled';
  courier: string;
  tracking: string;
  address: string;
  lines: { productId: string; quantity: number; price: number }[];
  events: { at: string; what: string }[];
}

export const orders: Order[] = [
  {
    id: 'DSK-24810',
    placed: '2026-03-08',
    status: 'shipped',
    courier: 'Swift Post',
    tracking: 'KN8841203377',
    address: '112 Cihampelas Street, Bandung 40131',
    lines: [
      { productId: 'daypack', quantity: 1, price: 540000 },
      { productId: 'wool-socks', quantity: 2, price: 135000 },
    ],
    events: [
      { at: '2026-03-11 09:12', what: 'Arrived at the Bandung warehouse' },
      { at: '2026-03-10 18:40', what: 'Left Jakarta' },
      { at: '2026-03-09 11:05', what: 'Handed to the courier' },
      { at: '2026-03-08 16:22', what: 'Order paid' },
    ],
  },
  {
    id: 'DSK-24796',
    placed: '2026-02-26',
    status: 'delivered',
    courier: 'Swift Post',
    tracking: 'KN8839114520',
    address: '112 Cihampelas Street, Bandung 40131',
    lines: [
      { productId: 'derby-shoes', quantity: 1, price: 890000 },
      { productId: 'leather-wallet', quantity: 1, price: 245000 },
    ],
    events: [
      { at: '2026-03-01 13:44', what: 'Received by the recipient' },
      { at: '2026-02-28 08:10', what: 'Out for delivery' },
      { at: '2026-02-27 07:55', what: 'Handed to the courier' },
      { at: '2026-02-26 20:31', what: 'Order paid' },
    ],
  },
  {
    id: 'DSK-24771',
    placed: '2026-02-14',
    status: 'processing',
    courier: 'Rapid Courier',
    tracking: '—',
    address: '8 Braga Street, Bandung 40111',
    lines: [{ productId: 'rain-jacket', quantity: 1, price: 575000 }],
    events: [{ at: '2026-02-14 10:02', what: 'Order paid' }],
  },
  {
    id: 'DSK-24702',
    placed: '2026-01-19',
    status: 'cancelled',
    courier: '—',
    tracking: '—',
    address: '8 Braga Street, Bandung 40111',
    lines: [{ productId: 'cabin-suitcase', quantity: 1, price: 1250000 }],
    events: [
      { at: '2026-01-20 09:30', what: 'Cancelled at the buyer\u2019s request' },
      { at: '2026-01-19 21:18', what: 'Awaiting payment' },
    ],
  },
];

/** The order status ramp, mapped once so no screen invents its own colours. */
export const orderTone = {
  processing: 'info',
  shipped: 'warning',
  delivered: 'success',
  cancelled: 'danger',
} as const;

/** A few reviews per product, so the detail page has something to show. */
export const reviews: Record<
  string,
  { by: string; stars: number; at: string; body: string }[]
> = {
  daypack: [
    {
      by: 'Fajar',
      stars: 5,
      at: '2026-02-20',
      body: 'Three months of daily use and the stitching is still neat.',
    },
    {
      by: 'Melati',
      stars: 4,
      at: '2026-01-30',
      body: 'Fits a 14-inch laptop, but the bottle pocket is a little tight.',
    },
  ],
  'derby-shoes': [
    {
      by: 'Rangga',
      stars: 5,
      at: '2026-02-02',
      body: 'They took two weeks to break in, and after that they are excellent.',
    },
  ],
  'round-glasses': [
    {
      by: 'Sinta',
      stars: 4,
      at: '2026-01-12',
      body: 'Light, and they do not slip down. The case is solid.',
    },
    {
      by: 'Bimo',
      stars: 5,
      at: '2025-12-28',
      body: 'Spring hinges, so they survive being sat on in a bag.',
    },
  ],
};
